version: '3'
services:
  db:
    build: ./Database
    container_name: db_videos_container
    ports:
      - "27017:27017"
    volumes:
      - "./Database/data:/data"
    command: mongod  
  backend:
    build: ./App
    container_name: backend_container
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://db:27017/videoApp
    links:
      - db
  frontend:
    build: ./Front
    container_name: front_container
    ports:
      - "3000:3000"
    links:
      - backend
